### ISSUE TITLE
brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by pavikaa** [reisxd/revanced-builder#13]
I'm getting the following output. Tried using different versions of the YT apk and the precompiled exe but it didn't help.
I'm using the builder without adb, installed latest node 18.4.0 and zulu 17.34.19.

`WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:6: error: resource android:color/background_cache_hint_selector_material_light is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:7: error: resource android:color/background_floating_material_dark is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:8: error: resource android:color/Blue_700 is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:9: error: resource android:color/Indigo_800 is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:10: error: resource android:color/GM2_grey_800 is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:11: error: resource android:color/Red_700 is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:12: error: resource android:color/Teal_700 is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:13: error: resource android:color/accent_device_default_dark_60_percent_opacity is private.
WARNING: C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\res\values-v31\colors.xml:14: error: resource android:color/autofill_background_material_dark is private.
WARNING: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\\AppData\Local\Temp\brut_util_Jar_125400259197730875146483487048822697.tmp, link, -o, C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530123712, --version-name, 17.25.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\\AppData\Local\Temp\APKTOOL5032270538945955797.tmp, -0, arsc, -I, C:\Users\\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\AndroidManifest.xml, C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:199)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:122)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\\AppData\Local\Temp\brut_util_Jar_125400259197730875146483487048822697.tmp, link, -o, C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530123712, --version-name, 17.25.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\\AppData\Local\Temp\APKTOOL5032270538945955797.tmp, -0, arsc, -I, C:\Users\\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\AndroidManifest.xml, C:\Users\\OneDrive\Desktop\revanced-builder\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more`

**Comment by reisxd** [comment]
Delete %localappdata%/ApkTool
