### ISSUE TITLE
Error while launching REVANCED after being built.

### ISSUE THREAD

**Issue by FeroxFoxxo** [reisxd/revanced-builder#325]
Clean install, cleared cache & storage of both YouTube and Temux. Built through Android.

```
time: 1661565375219
msg: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
stacktrace: java.lang.RuntimeException: Unable to get provider com.google.android.libraries.user.profile.photopicker.common.fileprovider.PhotoPickerFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
	at android.app.ActivityThread.installProvider(ActivityThread.java:7459)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7865)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
	at aaa.b(PG:43)
	at aaa.attachInfo(PG:10)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7454)
	... 11 more
```

**Comment by FeroxFoxxo** [comment]
Curious as to why this has been closed. Is it an issue from revanced's CLI? I can't manage to get it functional after the latest update.

**Comment by reisxd** [comment]
Because this isn't an issue with Builder but with patches.
