### ISSUE TITLE
Timeouts getting yt / ytmusic APK from apkmirror

### ISSUE THREAD

**Issue by marcelrv** [reisxd/revanced-builder#327]
**Describe the bug**
The 'download APK' screen fails to download apk, 
in the terminal I can see
```
GET /webfonts/fa-brands-400.woff2 200 2.406 ms - 105068
 GET /webfonts/fa-solid-900.woff2 200 3.128 ms - 330908
 [builder] An error occured.
FetchError: request to https://www.apkmirror.com/uploads/?appcategory=youtube-music failed, reason: connect ETIMEDOUT 198.41.0.4:443 at ClientRequest.<anonymous> (/snapshot/revanced-builder/node_modules/node-fetch/lib/index.js:1491:11) at ClientRequest.emit (node:events:527:28) at TLSSocket.socketErrorListener (node:_http_client:454:9) at TLSSocket.emit (node:events:527:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues. 
 [builder] An error occured. 
FetchError: request to https://www.apkmirror.com/uploads/?appcategory=youtube-music failed, reason: connect ETIMEDOUT 198.41.0.4:443 at ClientRequest.<anonymous> (/snapshot/revanced-builder/node_modules/node-fetch/lib/index.js:1491:11) at ClientRequest.emit (node:events:527:28) at TLSSocket.socketErrorListener (node:_http_client:454:9) at TLSSocket.emit (node:events:527:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.  
```

as it appears to face a timeout . Odd thing is that in with regular browser I can download the file without issues.

**To Reproduce**
After the selection of the app, and the patches..

1. The 'Select versions to download'
2. Click on ytmusic 5.16.51  (note also tried various other versions)
3. click continue
4. 'depending on the app selected, I can select the architecture
5. click continue
6. 'download APK' screen appears, but textbox remains empty
7. 

**Screenshots**

version:
[revanced-builder v3.3.2](https://github.com/reisxd/revanced-builder/releases/tag/v3.3.2)

**Desktop (please complete the following information):**

- OS: ubuntu 22

**Comment by reisxd** [comment]
Not an issue with Builder and also cannot reproduce.
