### ISSUE TITLE
TikTok and Warnwetter fail to read patches (android builder)

### ISSUE THREAD

**Issue by DaniAndTheWeb** [reisxd/revanced-builder#358]
On the latest release of the builder for android the program fails to read the avaiable patches for tiktok and for warnwetter.

Here is the log provided by the terminal when trying to read tiktok's patches:

TypeError: Cannot read properties of undefined (reading 'patches')
    at getPatchesList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:41:74)
    at getPatchList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:73:17)
    at getPatches (/data/data/com.termux/files/home/revanced-builder/wsEvents/getPatches.js:23:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:158:9)

**Comment by reisxd** [comment]
Fixed.
