### ISSUE TITLE
ReVanced Builder Android application "out"

### ISSUE THREAD

**Issue by reisxd** [reisxd/revanced-builder#392]
Hi everyone, because using Termux normally for some people was kinda too hard, I decided to make the Builder Android app (also for some other reasons)! If you want to use it, [download here from the latest workflow run](https://github.com/reisxd/termux-app/actions). Note that it might still have bugs and it's not really finished, there's still some features I wanna implement to this app. You can report any issue you find here.

**Comment by ElissonRodrigues** [comment]
## Report Info


**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2022-09-16 19:33:41.011 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[WebSocketSelector-541,5,main]`  
**Crash Timestamp**: `2022-09-16 19:33:38.600 UTC`  

**Crash Message**:
```
Attempt to invoke interface method 'java.net.InetSocketAddress org.java_websocket.WebSocket.getRemoteSocketAddress()' on a null object reference
```


### Stacktrace

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.net.InetSocketAddress org.java_websocket.WebSocket.getRemoteSocketAddress()' on a null object reference
	at com.termux.app.startup.WSS.onError(WSS.java:67)
	at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:687)
	at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:576)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:367)
	at com.termux.app.TermuxActivity$2.run(TermuxActivity.java:324)

```
##


## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `6.9.420+afd13c2`  
**VERSION_CODE**: `118`  
**UID**: `10848`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c80,c259,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c80,c259,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**TERMUX_APP_PACKAGE_MANAGER**: `APT`  
**TERMUX_APP_PACKAGE_VARIANT**: `APT_ANDROID_7`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##


## Device Info

### Software

**OS_VERSION**: `4.14.190-23974023-abM515FXXS4DVF2`  
**SDK_INT**: `31`  
**RELEASE**: `12`  
**ID**: `SP1A.210812.016`  
**DISPLAY**: `SP1A.210812.016.M515FXXS4DVF2`  
**INCREMENTAL**: `M515FXXS4DVF2`  
**SECURITY_PATCH**: `2022-06-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  
**MAX_PHANTOM_PROCESSES**: - (*Requires `DUMP` and `PACKAGE_USAGE_STATS` permission*)  
**MONITOR_PHANTOM_PROCS**: `<unsupported>`  
**DEVICE_CONFIG_SYNC_DISABLED**: -  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-M515F`  
**PRODUCT**: `m51nsxx`  
**BOARD**: `sm6150`  
**HARDWARE**: `qcom`  
**DEVICE**: `m51`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by BlasterOverlord** [comment]
Crashes on Android 7.0 😔

**Comment by reisxd** [comment]
> Crashes on Android 7.0 😔

[This one is the one that probably works](https://github.com/reisxd/termux-app/actions/runs/3013097270).

**Comment by BlasterOverlord** [comment]
> > Crashes on Android 7.0 😔
> 
> [This one is the one that probably works](https://github.com/reisxd/termux-app/actions/runs/3013097270).

What's the bootstrap zip there? Do I need to install that too?

**Comment by BlasterOverlord** [comment]
?

**Comment by shrihanDev** [comment]
Quick note:
The app **isn't usable**. So don't try to use it until it is said to.

**Comment by raaz2053** [comment]
![Screenshot_20221215-105150_Chrome](https://user-images.githubusercontent.com/20854983/207779098-a8cf4852-fe91-4100-92e3-33343b78ca52.jpg)
How cann i solve this

**Comment by Gestrid** [comment]
Looks like all the workflow runs are "expired" since they're old, so the APK can't be downloaded anymore.
