### ISSUE TITLE
Error during build process via Termux

### ISSUE THREAD

**Issue by SenseiSchizo** [reisxd/revanced-builder#427]
**Describe the bug**
The app fails to build on the latest update with the error message
`[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'useVer')
    at downloadApp (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:31:15)
    at getAppVersion (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:111:14)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:187:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.`

**To Reproduce**
1. Attempt to build via termux (using root, unable to verify if it is a root exclusive issue)
2. Build fails

**Screenshots**
![Screenshot_20220915-154211_Firefox Nightly](https://user-images.githubusercontent.com/106423063/190521202-9f5cd973-49e5-408a-ab01-11db0dbb13b2.png)

**revanced-builder:**  3.4.4

**Additional context**
Possibly related to #422

**Comment by HKC001** [comment]
Same error, also running 3.4.4.

[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'useVer')
    at downloadApp (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:31:15)
    at getAppVersion (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:111:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:187:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'useVer')
    at downloadApp (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:31:15)
    at getAppVersion (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:111:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:187:9)

**Comment by Dart2112** [comment]
Seems to be the same issue as #426

**Comment by SenseiSchizo** [comment]
Yes, seems to be a dupe. Closing.
