### ISSUE TITLE
Error when running on MacOS

### ISSUE THREAD

**Issue by simonjohnparker** [reisxd/revanced-builder#431]
MacOS Monterey 12.5

Worked fine for previous versions, updated to the latest and now getting this error:

`[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'useVer')
    at downloadApp (/snapshot/revanced-builder/wsEvents/getAppVersion.js:31:15)
    at getAppVersion (/snapshot/revanced-builder/wsEvents/getAppVersion.js:111:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/snapshot/revanced-builder/index.js:187:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.`

**Comment by shrihanDev** [comment]
Fixed in V3.4.5
