### ISSUE TITLE
[1.2.6] command fails

### ISSUE THREAD

**Issue by kzshantonu** [reisxd/revanced-builder#44]
```

An error occured.
Error: Command failed: java -jar ./revanced/revanced-cli-2.3.3-all.jar -b ./revanced/revanced-patches-2.11.0.jar --experimental -a ./revanced/youtube.apk  -o ./revanced/revanced.apk -m ./revanced/app-release-unsigned.apk  -e fenster-swipe-controls| Adds volume and brightness swipe controls.
 -e seekbar-tapping| Enables tapping on the seekbar of the YouTube player.
 -e hide-infocard-suggestions| Hides infocards in videos.
 -e autorepeat-by-default| Enables auto repeating of videos by default.
 -e custom-branding| Change the branding of YouTube.
 -e premium-heading| Show the premium branding on the the YouTube home screen.
 -e enable-wide-searchbar| Replaces the search icon with a wide search bar. This will hide the YouTube logo when active.
 -e hide-autoplay-button| Disables the autoplay button.
 -e enable-debugging| Enables app debugging by patching the manifest file.

/bin/sh: 1: Adds: not found
brut.androlib.AndrolibException: Could not load resources.arsc from file: ./revanced/youtube.apk
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:788)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:66)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:58)
        at brut.androlib.Androlib.getResTable(Androlib.java:74)
        at app.revanced.patcher.Patcher.<init>(Patcher.kt:59)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:115)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.directory.PathNotExist: resources.arsc
        at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:106)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:784)
        ... 14 more
/bin/sh: 2: -e: not found
/bin/sh: 2: Enables: not found
/bin/sh: 3: Hides: not found
/bin/sh: 3: -e: not found
/bin/sh: 4: Enables: not found
/bin/sh: 4: -e: not found
/bin/sh: 5: Change: not found
/bin/sh: 5: -e: not found
/bin/sh: 6: Show: not found
/bin/sh: 6: -e: not found
/bin/sh: 7: Replaces: not found
/bin/sh: 7: -e: not found
/bin/sh: 8: Disables: not found
/bin/sh: 8: -e: not found
/bin/sh: 9: Enables: not found
/bin/sh: 9: -e: not found

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'java -jar ./revanced/revanced-cli-2.3.3-all.jar -b ./revanced/revanced-patches-2.11.0.jar --experimental -a ./revanced/youtube.apk  -o ./revanced/revanced.apk -m ./revanced/app-release-unsigned.apk  -e fenster-swipe-controls| Adds volume and brightness swipe controls. \n' +
    ' -e seekbar-tapping| Enables tapping on the seekbar of the YouTube player. \n' +
    ' -e hide-infocard-suggestions| Hides infocards in videos. \n' +
    ' -e autorepeat-by-default| Enables auto repeating of videos by default. \n' +
    ' -e custom-branding| Change the branding of YouTube. \n' +
    ' -e premium-heading| Show the premium branding on the the YouTube home screen. \n' +
    ' -e enable-wide-searchbar| Replaces the search icon with a wide search bar. This will hide the YouTube logo when active. \n' +
    ' -e hide-autoplay-button| Disables the autoplay button. \n' +
    ' -e enable-debugging| Enables app debugging by patching the manifest file. \n',
  stdout: '',
  stderr: '/bin/sh: 1: Adds: not found\n' +
    'brut.androlib.AndrolibException: Could not load resources.arsc from file: ./revanced/youtube.apk\n' +
    '\tat brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:788)\n' +
    '\tat brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:66)\n' +
    '\tat brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:58)\n' +
    '\tat brut.androlib.Androlib.getResTable(Androlib.java:74)\n' +
    '\tat app.revanced.patcher.Patcher.<init>(Patcher.kt:59)\n' +
    '\tat app.revanced.cli.command.MainCommand.run(MainCommand.kt:115)\n' +
    '\tat picocli.CommandLine.executeUserObject(CommandLine.java:1939)\n' +
    '\tat picocli.CommandLine.access$1300(CommandLine.java:145)\n' +
    '\tat picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)\n' +
    '\tat picocli.CommandLine$RunLast.handle(CommandLine.java:2352)\n' +
    '\tat picocli.CommandLine$RunLast.handle(CommandLine.java:2314)\n' +
    '\tat picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)\n' +
    '\tat picocli.CommandLine$RunLast.execute(CommandLine.java:2316)\n' +
    '\tat picocli.CommandLine.execute(CommandLine.java:2078)\n' +
    '\tat app.revanced.cli.main.MainKt.main(Main.kt:7)\n' +
    'Caused by: brut.directory.PathNotExist: resources.arsc\n' +
    '\tat brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:106)\n' +
    '\tat brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:784)\n' +
    '\t... 14 more\n' +
    '/bin/sh: 2: -e: not found\n' +
    '/bin/sh: 2: Enables: not found\n' +
    '/bin/sh: 3: Hides: not found\n' +
    '/bin/sh: 3: -e: not found\n' +
    '/bin/sh: 4: Enables: not found\n' +
    '/bin/sh: 4: -e: not found\n' +
    '/bin/sh: 5: Change: not found\n' +
    '/bin/sh: 5: -e: not found\n' +
    '/bin/sh: 6: Show: not found\n' +
    '/bin/sh: 6: -e: not found\n' +
    '/bin/sh: 7: Replaces: not found\n' +
    '/bin/sh: 7: -e: not found\n' +
    '/bin/sh: 8: Disables: not found\n' +
    '/bin/sh: 8: -e: not found\n' +
    '/bin/sh: 9: Enables: not found\n' +
    '/bin/sh: 9: -e: not found\n'
}

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...

```

**Comment by reisxd** [comment]
It's about the endline of other OSes, #40 didn't fixed the issue completely. I'll fix it today and make a new release. Also fix the scraper.
