### ISSUE TITLE
WarnWetter patching crashes after dependency dowbload

### ISSUE THREAD

**Issue by r0ckarong** [reisxd/revanced-builder#442]
Whe trying to patch WarnWetter app, the builder gives an error after downloading the patches files.

``` An error occured:TypeError: Cannot read properties of undefined (reading 'patches') at getPatchesList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:50:5) at getPatchList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:82:17) at getPatches (/data/data/com.termux/files/home/revanced-builder/wsEvents/getPatches.js:23:31) at async WebSocket.
```

**Comment by reisxd** [comment]
Please give more information.

**Comment by r0ckarong** [comment]
The problem goes away after a reinstall of the builder.
