### ISSUE TITLE
3.4.7 [builder] SEVERE: sponsorblock failed: 

### ISSUE THREAD

**Issue by FadeMind** [reisxd/revanced-builder#448]
**Describe the bug**
[builder] SEVERE: sponsorblock failed: 

**To Reproduce**
part of **includedPatchesList.json**
```
{
  "packages": [
    {
      "name": "youtube",
      "patches": [
        "theme",
        "sponsorblock",
        "hide-cast-button",
        "video-ads",
        "general-ads",
        "microg-support",
        "remember-video-quality"
      ]
    },
```
build youtube

**Screenshots**

**revanced-builder Version:** 3.4.7

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context**
```
[builder] INFO: Decoding resources
[builder] INFO: Reading dex files
[builder] INFO: Merging .\revanced\revanced-integrations-v0.41.2.apk
[builder] INFO: Skipping custom-branding, reason: manually excluded
[builder] INFO: Skipping premium-heading, reason: manually excluded
[builder] INFO: Skipping old-quality-layout, reason: manually excluded
[builder] INFO: Skipping hide-autoplay-button, reason: manually excluded
[builder] INFO: Skipping hide-watermark, reason: manually excluded
[builder] INFO: Skipping disable-fullscreen-panels, reason: manually excluded
[builder] INFO: Skipping hide-create-button, reason: manually excluded
[builder] INFO: Skipping hide-shorts-button, reason: manually excluded
[builder] INFO: Skipping tablet-mini-player, reason: manually excluded
[builder] INFO: Skipping hide-time-and-seekbar, reason: manually excluded
[builder] INFO: Skipping return-youtube-dislike, reason: manually excluded
[builder] INFO: Skipping disable-auto-captions, reason: manually excluded
[builder] INFO: Skipping disable-auto-player-popup-panels, reason: manually excluded
[builder] INFO: Skipping enable-wide-searchbar, reason: manually excluded
[builder] INFO: Skipping hide-infocard-suggestions, reason: manually excluded
[builder] INFO: Skipping seekbar-tapping, reason: manually excluded
[builder] INFO: Skipping downloads, reason: manually excluded
[builder] INFO: Skipping swipe-controls, reason: manually excluded
[builder] INFO: Skipping settings, reason: manually excluded
[builder] INFO: Skipping minimized-playback, reason: manually excluded
[builder] INFO: Skipping custom-video-buffer, reason: manually excluded
[builder] INFO: Skipping custom-playback-speed, reason: manually excluded
[builder] INFO: Skipping client-spoof, reason: manually excluded
[builder] INFO: Skipping hdr-auto-brightness, reason: manually excluded
[builder] INFO: Skipping enable-debugging, reason: manually excluded
[builder] INFO: Skipping always-autorepeat, reason: manually excluded
[builder] WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp
[builder] WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping background-play, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping minimized-playback-music, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] INFO: Skipping compact-header, reason: excluded by default
[builder] WARNING: Skipping tasteBuilder-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping hide-get-premium, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping upgrade-button-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-microg-support, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping codecs-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping exclusive-audio-playback, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
[builder] WARNING: Skipping tiktok-feed-filter, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-settings, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-force-login, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
[builder] INFO: theme succeeded
[builder] SEVERE: sponsorblock failed:
[builder] app.revanced.patcher.patch.PatchResultError at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
[builder] at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.NullPointerException at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:329) at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:41) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326) ... 16 more
[builder] INFO: hide-cast-button succeeded
[builder] INFO: video-ads succeeded
[builder] INFO: general-ads succeeded
[builder] INFO: microg-support succeeded
[builder] INFO: remember-video-quality succeeded
[builder] INFO: Compiling resources
[builder] INFO: Writing modified dex files
[builder] INFO: Writing dex file classes4.dex
[builder] INFO: Writing dex file classes2.dex
[builder] INFO: Writing dex file classes3.dex
[builder] INFO: Writing dex file classes.dex
[builder] INFO: Writing dex file classes6.dex
[builder] INFO: Writing dex file classes7.dex
[builder] INFO: Writing dex file classes8.dex
[builder] INFO: Writing dex file classes5.dex
[builder] INFO: Writing resources...
[builder] INFO: Aligning revanced_raw.apk to revanced_aligned.apk
[builder] INFO: Signing revanced_aligned.apk to revanced_signed.apk
[builder] INFO: Copying revanced_signed.apk to revanced.apk
[builder] INFO: Finished
[builder] ReVanced has been built! Please transfer over revanced/ReVanced-YouTube-v17.37.35-cli_v2.11.1-patches_v2.66.2.apk and if you are using YT/YTM, revanced/microg.apk and install them!
```

**Comment by reisxd** [comment]
Not an issue with Builder.
