### ISSUE TITLE
Error Patching Tiktok 

### ISSUE THREAD

**Issue by MrCeez** [reisxd/revanced-builder#464]
Following log produced when trying to patch Tiktok on android using termux
Android 12 
Non root

[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'patches')
    at getPatchesList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:50:5)
    at getPatchList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:82:17)
    at getPatches (/data/data/com.termux/files/home/revanced-builder/wsEvents/getPatches.js:23:31)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:178:9)

**Comment by reisxd** [comment]
Delete the `includedPatchesList.json` file using:
```bash
rm revanced-builder/includedPatchesList.json
```
