### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by UnkreativerNutzername** [reisxd/revanced-builder#467]
**Describe the bug**
I don't really know how to describe. I just wanted to patch youtube apk and while patching this error occured.

**To Reproduce**

1. Just open the client
2. Go through the process, select patches etc
3. I choose the installed version (which is the recommended one)

**Log**

[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at Object.readSync (pkg/prelude/bootstrap.js:947:32)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at readFileSync (pkg/prelude/bootstrap.js:1082:36)
    at parsePatch (C:\snapshot\revanced-builder\utils\PatchesParser.js:9:5)
    at getPatches (C:\snapshot\revanced-builder\wsEvents\getPatches.js:28:24)
    at WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:178:15)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\snapshot\revanced-builder\node_modules\ws\lib\websocket.js:1178:20)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**revanced-builder Version:** [e.g. v3.4.8]

**Desktop (please complete the following information):**

- OS: Windows 10 but same error also occured on Zorin OS v9

**Comment by reisxd** [comment]
Could you try deleting the `revanced` folder?

**Comment by shrihanDev** [comment]
Closed as stale.
