### ISSUE TITLE
Type Error: Cannot read properties of undefined

### ISSUE THREAD

**Issue by rikinp93** [reisxd/revanced-builder#486]
Following error appears:
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'includes')
    at checkJDKAndADB (C:\snapshot\revanced-builder\utils\checkJDKAndADB.js:52:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async updateFiles (C:\snapshot\revanced-builder\wsEvents\updateFiles.js:71:8)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:162:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

Select the app you want to patch --> Youtube -> Downloading dependencies -> Failure

Screenshot:
https://prnt.sc/n9z4acLwjrqk

Version 3.4.13

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Comment by reisxd** [comment]
Could you open CMD and run `set NODE_DEBUG=child_process` then run Builder using `revanced-builder-win.exe`?

**Comment by shrihanDev** [comment]
Closing as stale.

**Comment by shrihanDev** [comment]
Closing as stale.
