### ISSUE TITLE
Select version YTM

### ISSUE THREAD

**Issue by Joxquin** [reisxd/revanced-builder#487]
**Describe the bug**
When you select the version of YTM this error jumps this error

Builder logs:
[builder] An error occured.
TypeError: Invalid Version: 5.26.20-CAR_RELEASE
    at new SemVer (C:\snapshot\revanced-builder\node_modules\semver\classes\semver.js:38:13)
    at compare (C:\snapshot\revanced-builder\node_modules\semver\functions\compare.js:3:32)
    at Object.lt (C:\snapshot\revanced-builder\node_modules\semver\functions\lt.js:2:29)
    at C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:175:12
    at Array.sort (<anonymous>)
    at getAppVersion (C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:174:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:183:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**revanced-builder Version:**
Lates

**Desktop:**

- OS: Windows
- Version: 11

**Comment by Joxquin** [comment]
I already saw another post similar to the issue

**Comment by Joxquin** [comment]
I already saw another post similar to the problem

**Comment by shrihanDev** [comment]
This is fixed in f8bbf647ff498f328cdc2bf8d08e0327d904ff41 via #485. Try using the latest version.
