### ISSUE TITLE
Error: EBUSY: resource busy or locked, unlink

### ISSUE THREAD

**Issue by techroy23** [reisxd/revanced-builder#502]
**Describe the bug**

**To Reproduce**

1. Ran *CMD*
2. Then ran the command *npm start* or *npm start run*
3. See error

**revanced-builder Version: 3.4.15** 
![image](https://user-images.githubusercontent.com/53241974/194688617-f798830c-3f12-474b-8dbe-a3afd1eaa451.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context**
Tried running on both non elevated and elevated cmd but still got the same result.

```[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\D:\_RevancedBuilderMain\revanced-cache\1.apk'
    at unlinkSync (node:fs:1775:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1270:10)
    at afterBuild (D:\_RevancedBuilderMain\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (D:\_RevancedBuilderMain\wsEvents\patchApp.js:219:53)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by reisxd** [comment]
Seems like that specific file is locked by an app and because Windows is windows, it'll never tell.

**Comment by shrihanDev** [comment]
APKTool is _probably_ holding that file for itself. Kill the `java` process from task manager and retry.
