### ISSUE TITLE
Error occurred after downloading patches

### ISSUE THREAD

**Issue by Vucko130** [reisxd/revanced-builder#510]
**Describe the bug**
[builder] An error occured.
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsePatch (C:\snapshot\revanced-builder\utils\PatchesParser.js:8:28)
    at getPatches (C:\snapshot\revanced-builder\wsEvents\getPatches.js:28:24)
    at WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:174:15)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\snapshot\revanced-builder\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (C:\snapshot\revanced-builder\node_modules\ws\lib\receiver.js:528:14)
    at Receiver.getData (C:\snapshot\revanced-builder\node_modules\ws\lib\receiver.js:446:17)
    at Receiver.startLoop (C:\snapshot\revanced-builder\node_modules\ws\lib\receiver.js:148:22)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**To Reproduce**

Select Youtube and download the patches. after that this error occurs. I am using the latest version of the builder.

**Screenshots**
![image](https://user-images.githubusercontent.com/92352731/195995694-26278004-676e-48f7-91dc-7f377d06baf7.png)
![image](https://user-images.githubusercontent.com/92352731/195995852-f6b3e959-97ff-4c6b-acc4-609bf0876717.png)

**revanced-builder Version: 3.4.15** 

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Comment by reisxd** [comment]
Could you show the `revanced-patches-vx.x.x.json` file?

**Comment by Vucko130** [comment]
you're right. That downloaded incorrectly. Inside that file was Server Down written.
