### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by KROCKcorp** [reisxd/revanced-builder#524]
at Object.readSync (node:fs:727:3)
    at Object.readSync (pkg/prelude/bootstrap.js:947:32)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at readFileSync (pkg/prelude/bootstrap.js:1082:36)
    at parsePatch (C:\snapshot\revanced-builder\utils\PatchesParser.js:9:5)
    at getPatches (C:\snapshot\revanced-builder\wsEvents\getPatches.js:28:24)
    at WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:178:15)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\snapshot\revanced-builder\node_modules\ws\lib\websocket.js:1178:20)

**Comment by shrihanDev** [comment]
Delete the `revanced/` folder and try again.
