### ISSUE TITLE
Failed to patch video-ads

### ISSUE THREAD

**Issue by arihid** [reisxd/revanced-builder#530]
**Describe the bug**
Patcher fails to patch video-ads in the builder. Failure happened when patching these versions: 17.40.41, 17.41.37, 17.42.34. I conclude that the bug is persistent if it happened in multiple consecutive run of multiple base versions. In version 17.42.34, hide-crowdfunding-box is also failed, but that version is considered beta.

**To Reproduce**

Operate as you would. Patch error will show in log.

**Screenshots**
![gambar](https://user-images.githubusercontent.com/82217590/198419154-25fc500a-fc33-463d-9cfc-9dec934a69d4.png)

**revanced-builder Version:** 
3.4.15

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context**
Here is the log:
```
[builder] SEVERE: Failed to delete existing resource cache directory
***
[builder] SEVERE: video-ads failed:
[builder] app.revanced.patcher.patch.PatchResultError at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:346) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: java.lang.NullPointerException at app.revanced.patches.youtube.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:44) at app.revanced.patches.youtube.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:22) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:342) ... 16 more

**Comment by dimon222** [comment]
https://github.com/revanced/revanced-patches/pull/878#issuecomment-1294273551
