### ISSUE TITLE
Reddit patching error

### ISSUE THREAD

**Issue by Tasin5541** [reisxd/revanced-builder#585]
**Describe the bug**
Getting error whenever I try to patch reddit. YouTube isn't working either. 

**Log**
```
[builder] INFO: Reading dex files
[builder] WARNING: Skipping package group: com.reddit.frontpage.creatorkit_dynamicfeature
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7e0c0000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7e0e0000
[builder] INFO: Skipping sim-spoof, reason: excluded by default
[builder] INFO: Skipping compact-header, reason: excluded by default
[builder] INFO: Skipping debug-mode, reason: excluded by default
[builder] INFO: Skipping theme, reason: excluded by default
[builder] INFO: Skipping premium-icon-reddit, reason: manually excluded
[builder] WARNING: Skipping predictive-back-gesture, reason: Missing compatibility annotation. Continuing.
[builder] WARNING: Skipping package group: com.reddit.frontpage.creatorkit_dynamicfeature
[builder] INFO: Deleting existing resource cache directory
[builder] INFO: Decoding resources
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7e0c0000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7e0e0000
[builder] INFO: general-reddit-ads succeeded
[builder] INFO: predictive-back-gesture succeeded
[builder] INFO: Compiling resources
[builder] WARNING: aapt2 W 12-14 17:45:52 5202 5202] Unknown chunk type '200'.
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/AndroidManifest.xml:695: error: unexpected element found in .
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/AndroidManifest.xml:696: error: unexpected element found in .
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/AndroidManifest.xml:697: error: unexpected element found in .
[builder] WARNING: /data/data/com.termux/files/home/revanced-builder/./revanced-cache/AndroidManifest.xml:698: error: unexpected element found in .
[builder] brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/revanced-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 648277, --version-name, 2022.43.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL13771309017595920224.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/build/resources.zip] at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494) at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629) at app.revanced.patcher.Patcher.save(Patcher.kt:148) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:33) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/revanced-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 33, --version-code, 648277, --version-name, 2022.43.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL13771309017595920224.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revanced-builder/./revanced-cache/build/resources.zip] at brut.util.OS.exec(OS.java:99) at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490) ... 13 more
```

**revanced-builder Version:** 3.5.0

- OS: Android
- Version: 12

**Additional context**

**Comment by reisxd** [comment]
You'll have to exclude Predictive Back Gesture patch. Closing.

**Comment by Tasin5541** [comment]
> You'll have to exclude Predictive Back Gesture patch. Closing.

There is no Predictive Back Gesture patch available on the patch selection screen.

**Comment by reisxd** [comment]
> > You'll have to exclude Predictive Back Gesture patch. Closing.
> 
> There is no Predictive Back Gesture patch available on the patch selection screen.

Update Builder.

**Comment by Tasin5541** [comment]
> > > You'll have to exclude Predictive Back Gesture patch. Closing.
> > 
> > 
> > There is no Predictive Back Gesture patch available on the patch selection screen.
> 
> Update Builder.

I'm already using the latest version (3.5.0)

**Comment by reisxd** [comment]
> > > > You'll have to exclude Predictive Back Gesture patch. Closing.
> > > 
> > > 
> > > There is no Predictive Back Gesture patch available on the patch selection screen.
> > 
> > 
> > Update Builder.
> 
> I'm already using the latest version (3.5.0)

Again, update Builder. There's new commits.
