### ISSUE TITLE
Request to change the exitProcess function

### ISSUE THREAD

**Issue by ShreeyansB** [reisxd/revanced-builder#59]
I am trying to automate the prompts for the compiled executable. This is the command that im using:
```bash
echo -ne '\n\n' | ./revanced-builder-nodejs-linux --patch 
```
This works fine but when the program comes to and end i.e _Press any key to exit..._, I get an infinite loop of this error:
```
TypeError: process.stdin.setRawMode is not a function
at exitProcess (/snapshot/revanced-builder/index.js:43:17)
at process.<anonymous> (/snapshot/revanced-builder/index.js:38:9)
at process.emit (node:events:527:28)
at processEmit [as emit] (/snapshot/revanced-builder/node_modules/signal-exit/index.js:199:34)
at emit (node:internal/process/promises:140:20)
at processPromiseRejections (node:internal/process/promises:274:27)
at processTicksAndRejections (node:internal/process/task_queues:97:32)

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
```
I guess when Im send my input to stdin, I doesnt allow nodejs to setRawMode to true [here](https://github.com/reisxd/revanced-builder/blob/0c810323defd21dd70055d1047d05d3cdd261603/index.js#L43).
Would be nice if you could change this function to not use setRawMode

**Comment by reisxd** [comment]
I cannot replace it, because theres no equvialent of `process.stdin.setRawMode` in NodeJS API. Also, you still can't make your script fully automatic because of the YT Version selector.
