### ISSUE TITLE
Unable to patch youtube after the recent update

### ISSUE THREAD

**Issue by 1Phase1** [reisxd/revanced-builder#595]
**Describe the bug**
After the latest patch, when attempting to patch Youtube, Builder fails with a Java exception every time.

**To Reproduce**

1. Run the latest version of Revanced Builder
2. Select any patches
3. Select youtube 1.45.36
4. Error below appears not long after patching begins

"[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/data/ContextKt at app.revanced.patches.youtube.misc.video.information.patch.VideoInformationPatch.execute(VideoInformationPatch.kt:101) at app.revanced.patches.youtube.misc.video.information.patch.VideoInformationPatch.execute(VideoInformationPatch.kt:30) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:399) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.data.ContextKt at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)"

**revanced-builder Version:**
3.6.0

**Additional context**
Desktop information is not provided as the mobile version of Builder is in use. Android version is 12 and Termux is being used to run the Builder.

**Comment by StrPlayer** [comment]
having same issue with youtube and tiktok

**Comment by reisxd** [comment]
Dupe of #593.
