### ISSUE TITLE
Error while patching multiple apps 

### ISSUE THREAD

**Issue by rohitghali** [reisxd/revanced-builder#600]
**Describe the bug**
while patching windy or twitter etc, after it says found existing keystore it shows an error.

**revanced-builder Version:** 
3.6.0

` An error occured:Error: Command failed: cp /data/data/com.termux/files/home/revanced-builder/revanced/ReVanced-Windy.app: wind & weather live-v33.1.4-arm64-v8a-cli_v2.18.1-patches_v2.144.0.apk /storage/emulated/0/ReVanced-Windy.app: wind & weather live-v33.1.4-arm64-v8a-cli_v2.18.1-patches_v2.144.0.apk/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/usr/bin/sh: 1: weather: not foundweather: not foundcp: cannot stat '/data/data/com.termux/files/home/revanced-builder/revanced/ReVanced-Windy.app:': No such file or directoryat ChildProcess.exithandler (node:child_process:402:12)at ChildProcess.emit (node:events:513:28)at maybeClose (node:internal/child_process:1100:16)at Socket.`

**Comment by rohitghali** [comment]
`[builder] Opening the app in the default browser... Done, check if a browser window has opened
Not sure what to do with typed value of type 0x4, falling back to reading an uint32.
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'replace')
    at outputName (/data/data/com.termux/files/home/revanced-builder/wsEvents/patchApp.js:91:119)
    at afterBuild (/data/data/com.termux/files/home/revanced-builder/wsEvents/patchApp.js:29:3)
    at Socket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/wsEvents/patchApp.js:182:53)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
[builder] An error occured.
Error: ENOENT: no such file or directory, rename '/data/data/com.termux/files/home/revanced-builder/revanced/revanced.apk' -> '/data/data/com.termux/files/home/revanced-builder/revanced/ReVanced-Windy.app: wind & weather live-vinc/twitter/twitter.9.65.7.release.0-arm64-v8a-cli_v2.18.1-patches_v2.144.0.apk'
    at renameSync (node:fs:1026:3)
    at afterBuild (/data/data/com.termux/files/home/revanced-builder/wsEvents/patchApp.js:30:3)
    at Socket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/wsEvents/patchApp.js:182:53)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
[builder] An error occured.
Error: Command failed: cp /data/data/com.termux/files/home/revanced-builder/revanced/ReVanced-Windy.app: wind & weather live-v33.1.4-arm64-v8a-cli_v2.18.1-patches_v2.144.0.apk /storage/emulated/0/ReVanced-Windy.app: wind & weather live-v33.1.4-arm64-v8a-cli_v2.18.1-patches_v2.144.0.apk
/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/usr/bin/sh: 1: weather: not foundweather: not found

cp: cannot stat '/data/data/com.termux/files/home/revanced-builder/revanced/ReVanced-Windy.app:': No such file or directory

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.`

**Comment by reisxd** [comment]
Fixed in ba10b2b3fbf97c89b3e5a4fdf2399858c6c68dfa.
