### ISSUE TITLE
Patching Error While Patching Any Version Of TikTok

### ISSUE THREAD

**Issue by ShoraiK** [reisxd/revanced-builder#605]
I'm not sure if it's similar to #603 but it happens when patching any version of the TikTok app.

**revanced-builder Version:** v3.6.1

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 (22H2)

**Additional context**
```
[builder] INFORMACI�N: Reading dex files
[builder] INFORMACI�N: Decoding AndroidManifest.xml only, because resources are not needed
[builder] ADVERTENCIA: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
[builder] INFORMACI�N: Merging C:\Users\Segov\Desktop\ReVanced\revanced\revanced-integrations-v0.84.0.apk
[builder] INFORMACI�N: Skipping sim-spoof: Manually excluded
[builder] INFORMACI�N: Deleting existing resource cache directory
[builder] GRAVE: Failed to delete existing resource cache directory
[builder] INFORMACI�N: Decoding resources
[builder] ADVERTENCIA: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] ADVERTENCIA: Cant find 9patch chunk in file: "o/gl.9.png". Renaming it to *.png.
[builder] INFORMACI�N: disable-login-requirement succeeded
[builder] GRAVE: downloads failed:
[builder] app.revanced.patcher.patch.PatchResultError: 'downloads' depends on 'settings' but the following error was raised: Hardcode offset changed.
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:404) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
[builder] at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] GRAVE: feed-filter failed: app.revanced.patcher.patch.PatchResultError: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:404) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
[builder] at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] INFORMACI�N: fix-google-login succeeded
[builder] INFORMACI�N: hide-ads succeeded
[builder] Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/data/ContextKt
[builder] at app.revanced.patches.tiktok.interaction.speed.patch.PlaybackSpeedPatch.execute(PlaybackSpeedPatch.kt:34) at app.revanced.patches.tiktok.interaction.speed.patch.PlaybackSpeedPatch.execute(PlaybackSpeedPatch.kt:18) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.data.ContextKt at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ... 19 more
```

**Comment by reisxd** [comment]
Dupe of #593.
