### ISSUE TITLE
Bug In Patch In Android

### ISSUE THREAD

**Issue by Parsa307** [reisxd/revanced-builder#607]
**Describe the bug**
[builder] An error occured.
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at normalizeSpawnArguments (node:child_process:528:3)
    at spawn (node:child_process:726:13)
    at patchApp (/data/data/com.termux/files/home/revanced-builder/wsEvents/patchApp.js:175:24)
    at WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:203:15)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/data/data/com.termux/files/home/revanced-builder/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/data/data/com.termux/files/home/revanced-builder/node_modules/ws/lib/receiver.js:528:14)
**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v3.6.1]

**Desktop (please complete the following information):**

- OS: [e.g. Android]
- Version: [12]

**Additional context**

**Comment by reisxd** [comment]
Reproducing steps not met.
