### ISSUE TITLE
android "file string" argument error at patch stage

### ISSUE THREAD

**Issue by jap2slow** [reisxd/revanced-builder#608]
**Describe the bug**

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at normalizeSpawnArguments (node:child_process:528:3)
    at spawn (node:child_process:726:13)
    at patchApp (/data/data/com.termux/files/home/revanced-builder/wsEvents/patchApp.js:175:24)
    at WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:203:15)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/data/data/com.termux/files/home/revanced-builder/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/data/data/com.termux/files/home/revanced-builder/node_modules/ws/lib/receiver.js:528:14)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**To Reproduce**

Tried with both npm  8.19.2 and 9.2.0 as termix mentions update available 

After the first error did a fresh termix install(cleaned cache and storage) and followed the build commands.
Downloaded dependency
Selected to patch app( tried YouTube and twitch) both trigger error
Tried different versions
Selected what to patch( all and non) both trigger error

The moment the local:8000/patch appears it trows the file string error

Screenshots

revanced-builder Version: [v3.6.1]

Desktop (please complete the following information):

    OS: [Android]
    Version: [10]

**Additional context**

**Comment by jap2slow** [comment]
Reverted patchapp.js row 175 back to 'java' as from before "parent 1a7e56e commit e3954f26544a90857eeb7a9ede62e1e545cfc9de" and it works again.
Zulu Java does not work in android termix

**Comment by reisxd** [comment]
@shrihanDev guh

**Comment by shrihanDev** [comment]
@reisxd AAAAAAAAAA-
