### ISSUE TITLE
Revanced Builder Bug In Ubuntu

### ISSUE THREAD

**Issue by Parsa307** [reisxd/revanced-builder#615]
Not sure what to do with typed value of type 0x4, falling back to reading an uint32.
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'replace')
    at outputName (/snapshot/revanced-builder/wsEvents/patchApp.js:94:35)
    at afterBuild (/snapshot/revanced-builder/wsEvents/patchApp.js:29:3)
    at Socket.<anonymous> (/snapshot/revanced-builder/wsEvents/patchApp.js:185:53)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by git-Hmmm** [comment]
@Parsa307 Can you please tell that which app you were trying to patch? and Which version?

**Comment by Parsa307** [comment]
Youtube

**Comment by Parsa307** [comment]
Revanced Manager Can Patch Youtube
But Revanced Bulider Don't Work

**Comment by Parsa307** [comment]
Used Upload Button And Select Apk To Patch Youtube

**Comment by rocknjoekudo** [comment]
I can confirm that I have the same when I patch Twitter using **Upload Apk** function. The OS is **Ubuntu 22.04.1** .

**Comment by theonlyonerzk** [comment]
hey, I have the same issue but in Termux, whenever I try to patch YouTube (17.49.37) it always gets an error like this:

![Screenshot_2022-12-24-12-20-32-297_com brave browser](https://user-images.githubusercontent.com/61009872/209421004-05e4087c-efee-48d9-9004-3494f9497dbe.jpg)

**Comment by shrihanDev** [comment]
Attempted to fix in 585c774.
Run `./revanced-builder.sh update` if on Termux or download the newest release if on desktop!
