### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Miosp** [reisxd/revanced-builder#623]
After normal patching process, there is an error:
Here is console output:
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
Not sure what to do with typed value of type 0x4, falling back to reading an uint32.
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'replace')
    at outputName (C:\snapshot\revanced-builder\wsEvents\patchApp.js:94:35)
    at afterBuild (C:\snapshot\revanced-builder\wsEvents\patchApp.js:29:3)
    at Socket.<anonymous> (C:\snapshot\revanced-builder\wsEvents\patchApp.js:185:53)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

1. Normally go through steps to patch YouTube Apk

**revanced-builder Version:** 3.7

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Comment by Miosp** [comment]
Probably a duplicate of this ubuntu one, sry im blind.
