### ISSUE TITLE
Error in select app to patch stage

### ISSUE THREAD

**Issue by HotCakeX** [reisxd/revanced-builder#644]
**Describe the bug**
I get this error on app selection step

**To Reproduce**

1. select start patching
2. wait for dependency downloading to succeed
3. in the select app to patch, I get the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/118815227/214308612-92fb147c-b4af-4167-852f-3d78a531d628.png)

**revanced-builder Version:** [e.g. v1.2.10]

- Windows 11 build 25281
- zulu19.30.11-ca-jdk19.0.1-win_x64
- Revanced builder 3.8.0

```
[builder] Listening at port 8002
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at C:\snapshot\revanced-builder\node_modules\node-fetch\lib\index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchPackages (C:\snapshot\revanced-builder\wsEvents\getApp.js:19:20)
    at async getPatches (C:\snapshot\revanced-builder\wsEvents\getApp.js:40:16)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:175:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

```

**Comment by stefano99** [comment]
It happens to me too, using Termux on Android.
