### ISSUE TITLE
An error occured. FetchError: invalid json response

### ISSUE THREAD

**Issue by UmRAtEJvgLtH** [reisxd/revanced-builder#661]
I'm using the latest exe on Windows of the revanced-builder. It worked the day before yesterday but since yesterday i get this error:

[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at C:\snapshot\revanced-builder\node_modules\node-fetch\lib\index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchPackages (C:\snapshot\revanced-builder\wsEvents\getApp.js:19:20)
    at async getPatches (C:\snapshot\revanced-builder\wsEvents\getApp.js:40:16)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:175:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by UmRAtEJvgLtH** [comment]
I don't understand the remarkt "closed as not planned". What does this mean?
