### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by iSaidyiu** [reisxd/revanced-builder#683]
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at C:\snapshot\revanced-builder\node_modules\node-fetch\lib\index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (C:\snapshot\revanced-builder\wsEvents\getApp.js:19:20)
    at async getPatches (C:\snapshot\revanced-builder\wsEvents\getApp.js:40:16)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:175:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

![image](https://user-images.githubusercontent.com/12668297/231684598-6f75c273-bbe6-4d2b-bdc9-b61ee62b8c5d.png)

**Comment by shrihanDev** [comment]
Delete everything and start from scratch.
