### ISSUE TITLE
Compilaton error

### ISSUE THREAD

**Issue by lucastwg** [reisxd/revanced-builder#684]
[builder] An error occured:
Error: EBUSY: resource busy or locked, unlink '\\?\D:\Users\xxxx\Downloads\vanced\revanced-cache\1.apk'
at unlinkSync (node:fs:1780:3)
at _unlinkSync (node:internal/fs/rimraf:214:14)
at rimrafSync (node:internal/fs/rimraf:195:7)
at node:internal/fs/rimraf:253:9
at Array.forEach ()
at _rmdirSync (node:internal/fs/rimraf:250:7)
at rimrafSync (node:internal/fs/rimraf:193:7)
at rmSync (node:fs:1274:10)
at afterBuild (C:\snapshot\revanced-builder\wsEvents\patchApp.js:28:3)
at Socket. (C:\snapshot\revanced-builder\wsEvents\patchApp.js:186:53)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

Error happens at the very end, after applying all patches and signing, using external Youtube apk since the ones listed aren't compatible (Need 18.05.40 but the versions provided don't go that low). Have tried multiple Youtube apks to no success.

Edit for temp fix: You can use "revanced_signed.apk" in \revanced-cache, works as normal.

**Comment by shrihanDev** [comment]
Closed via c2707da6996a7b7f3a172a31e6888660a8f839f4
