### ISSUE TITLE
error occured

### ISSUE THREAD

**Issue by alpheus10** [reisxd/revanced-builder#688]
[builder] An error occured.
Error: EPERM: operation not permitted, open 'settings.json'
    at Object.openSync (node:fs:599:3)
    at Object.openSync (pkg/prelude/bootstrap.js:793:32)
    at writeFileSync (node:fs:2221:35)
    at createSettingsFile (C:\snapshot\revanced-builder\utils\Settings.js:13:3)
    at getSources (C:\snapshot\revanced-builder\utils\Settings.js:86:5)
    at getSettings (C:\snapshot\revanced-builder\wsEvents\getSettings.js:7:20)
    at WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:211:15)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (C:\snapshot\revanced-builder\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:537:28)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by shrihanDev** [comment]
Delete everything and start from scratch.
Make sure you have write permissions to the folder you're using for the Builder.
