### ISSUE TITLE
Patching failure

### ISSUE THREAD

**Issue by baigrawaha** [reisxd/revanced-builder#693]
I have been trying to patch the YouTube. I am getting 2 common errors. 
`[builder] SEVERE: video-ads failed: app.revanced.patcher.patch.PatchResultError: 'video-ads' depends on 'settings' but the following error was raised: 'settings' did not succeed previously at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)`
 
and 

`[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\rawah\Downloads\Programs\Revanced Builder\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\revanced-builder\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\revanced-builder\wsEvents\patchApp.js:186:53)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.`

YT version: 18.05.40

**Comment by imgodfrey101** [comment]
Same here.
