### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by WirelessAlien** [reisxd/revanced-builder#701]
An error occured:Error: EPERM: operation not permitted, rename './revanced/temp.apk' -> './revanced/com.google.android.youtube.apk'at renameSync (node:fs:1038:3)at C:\snapshot\revanced-builder\utils\uploadAPKFile.js:23:11at process.processTicksAndRejections (node:internal/process/task_queues:95:5)Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
**revanced-builder Version:** Latest

**Desktop (please complete the following information):**

- OS: [Windows]
- Version: [10]

**Comment by plasma3000** [comment]
have you tried roll back to v3.9.0?

**Comment by WirelessAlien** [comment]
> have you tried roll back to v3.9.0? 

Yeah, didn't work. I don't know maybe it's a problem with my laptop that's why I used cli later.

**Comment by SangeethSujith** [comment]
> have you tried roll back to v3.9.0?

i rolled back the build was successful but there is no apk in the files

**Comment by mOHITH998** [comment]
> An error occured:Error: EPERM: operation not permitted, rename './revanced/temp.apk' -> './revanced/com.google.android.youtube.apk'at renameSync (node:fs:1038:3)at C:\snapshot\revanced-builder\utils\uploadAPKFile.js:23:11at process.processTicksAndRejections (node:internal/process/task_queues:95:5)Please report this bug here: https://github.com/reisxd/revanced-builder/issues. **revanced-builder Version:** Latest
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Windows]
> * Version: [10]
> 
> I don't know why this is happening

### IT WORKED FOR ME!

1.  Download youtube apk from apkmirror website

### OR

2. Try patching with revanced-builder v3.9.0

### Both of them works (see screenshot)
![brave_zkbTpYMp6m](https://user-images.githubusercontent.com/67540679/234496857-e26d3430-0072-4a4b-b0a8-5659bf048443.png)

**Comment by SangeethSujith** [comment]
3.8.0 is the best version use that
