### ISSUE TITLE
Loading apps error

### ISSUE THREAD

**Issue by zjunior06** [reisxd/revanced-builder#724]
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at /data/data/com.termux/files/home/revanced-builder/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (/data/data/com.termux/files/home/revanced-builder/wsEvents/getApp.js:19:20)
    at async getPatches (/data/data/com.termux/files/home/revanced-builder/wsEvents/getApp.js:40:16)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:175:9)

**Comment by rochatisaac** [comment]
That issue is related to the use of VPN. Try disconnecting before proceeding

**Comment by zjunior06** [comment]
Solved
