### ISSUE TITLE
Revanced-builder unable to start

### ISSUE THREAD

**Issue by TheRedNet** [reisxd/revanced-builder#741]
OS: windows11 x64
builder version: 3.9.2
LOG:

`
PS D:\programms\ReVancedInstaller> .\revanced-builder-win.exe
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module 'fkill'
Require stack:
- C:\snapshot\revanced-builder\wsEvents\patchApp.js
- C:\snapshot\revanced-builder\wsEvents\index.js
- C:\snapshot\revanced-builder\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\revanced-builder\wsEvents\patchApp.js:10:15)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\revanced-builder\\wsEvents\\patchApp.js',
    'C:\\snapshot\\revanced-builder\\wsEvents\\index.js',
    'C:\\snapshot\\revanced-builder\\index.js'
  ],
  pkg: true
}

Node.js v18.5.0
PS D:\programms\ReVancedInstaller> .\revanced-builder-win.exe
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module 'fkill'
Require stack:
- C:\snapshot\revanced-builder\wsEvents\patchApp.js
- C:\snapshot\revanced-builder\wsEvents\index.js
- C:\snapshot\revanced-builder\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\revanced-builder\wsEvents\patchApp.js:10:15)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\revanced-builder\\wsEvents\\patchApp.js',
    'C:\\snapshot\\revanced-builder\\wsEvents\\index.js',
    'C:\\snapshot\\revanced-builder\\index.js'
  ],
  pkg: true
}

Node.js v18.5.0
PS D:\programms\ReVancedInstaller> .\revanced-builder-win.exe
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
PS D:\programms\ReVancedInstaller> .\revanced-builder-win.exe
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module 'fkill'
Require stack:
- C:\snapshot\revanced-builder\wsEvents\patchApp.js
- C:\snapshot\revanced-builder\wsEvents\index.js
- C:\snapshot\revanced-builder\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\revanced-builder\wsEvents\patchApp.js:10:15)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\revanced-builder\\wsEvents\\patchApp.js',
    'C:\\snapshot\\revanced-builder\\wsEvents\\index.js',
    'C:\\snapshot\\revanced-builder\\index.js'
  ],
  pkg: true
}

Node.js v18.5.0
`

**Comment by 1Phase1** [comment]
Can confirm that I'm getting this exact same issue on Termux in Android

**Comment by ntcong** [comment]
`fkill` was removed in this (https://github.com/reisxd/revanced-builder/commit/375c863cfaed4be70ee259877d551c9fc55f3f9c) but is still required in this module https://github.com/reisxd/revanced-builder/blob/main/wsEvents/patchApp.js

**Comment by Zoey2936** [comment]
Running from source with fkill readed fixed it. (But: https://github.com/reisxd/revanced-builder/blob/375c863cfaed4be70ee259877d551c9fc55f3f9c/wsEvents/checkForUpdates.js#L3) still has the wrong version number
