### ISSUE TITLE
Error while building Revanced

### ISSUE THREAD

**Issue by ShreeyansB** [reisxd/revanced-builder#80]
Im getting this in the error log while building revanced using v2.0.1:
```
INFO: Decoding resources 
INFO: Reading dex files 
INFO: Merging .\revanced\app-release-unsigned.apk 
WARNING: Skipping music-video-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
...
INFO: Skipping hdr-auto-brightness: Not explicitly included 
...
INFO: hide-watermark succeeded 
INFO: Compiling resources 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:6: error: resource android:color/background_cache_hint_selector_material_light is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:7: error: resource android:color/background_floating_material_dark is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:8: error: resource android:color/Blue_700 is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:9: error: resource android:color/Indigo_800 is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:10: error: resource android:color/GM2_grey_800 is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:11: error: resource android:color/Red_700 is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:12: error: resource android:color/Teal_700 is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:13: error: resource android:color/accent_device_default_dark_60_percent_opacity is private. 
WARNING: C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\res\values-v31\colors.xml:14: error: resource android:color/autofill_background_material_dark is private. 
WARNING: error: failed linking references. 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SHREEY~1\AppData\Local\Temp\brut_util_Jar_45265513389682135623552912986005770812.tmp, link, -o, C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530516928, --version-name, 17.28.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\SHREEY~1\AppData\Local\Temp\APKTOOL15559747936907822270.tmp, -0, arsc, -I, C:\Users\shreeyans\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\AndroidManifest.xml, C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\build\resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
	at app.revanced.patcher.Patcher.save(Patcher.kt:199)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SHREEY~1\AppData\Local\Temp\brut_util_Jar_45265513389682135623552912986005770812.tmp, link, -o, C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530516928, --version-name, 17.28.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\SHREEY~1\AppData\Local\Temp\APKTOOL15559747936907822270.tmp, -0, arsc, -I, C:\Users\shreeyans\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\AndroidManifest.xml, C:\Users\shreeyans\Documents\Software\ReVanced\revanced-cache\build\resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
	... 13 more
```

Seems like a problem with apktool

My Dependencies:
```bash
C:\>java --version
openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)

C:\>node -v
v16.16.0
```

**Comment by reisxd** [comment]
Delete %localappdata%/ApkTool.

**Comment by ShreeyansB** [comment]
Thanks a lot

**Comment by greatwitedragon** [comment]
How do i do this on web version
