### ISSUE TITLE
Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by akiyuee** [reisxd/revanced-builder#99]
**Describe the bug**
RevancedBuilder threw 
```
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
``` 
during building the apk file.

**To Reproduce**
I followed exactly the termux installation instructions and excluded "custom-branding".

**Screenshots**
<details><summary>It's long</summary>

![Screenshot_20220728-182355_Termux](https://user-images.githubusercontent.com/67498765/181494910-14b97879-2c11-4cd7-bc1c-b97679a6af99.jpg)

</details>

**revanced-builder Version:** lastest

**Desktop (please complete the following information):**

- OS: Android (Termux)

**Additional context**
![Screenshot_20220728-182723_Termux](https://user-images.githubusercontent.com/67498765/181494375-b8d6972a-7587-46a8-97a7-f48aa06c5184.jpg)

<details><summary>Installation Logs</summary>

```
~/etc/revanced-builder-cli $ node .
Downloading required files...
[app-release-unsigned.apk] ✓
[microg.apk] ✓
revanced-builder has detected that you are using Android (Termux)!
JDK is already installed.
Checking for aapt2... aapt2 is already installed.
? Select what app you want to patch: YouTube
? Select the patches you want to exclude. custom-branding |
Changes the YouTube launcher icon to be ReVanced's.
? Select the version to download. 17.29.34
Downloading the APK, this'll take some time!
[youtube.apk] ✓
Download complete!
Building ReVanced, please be patient!
An error occured.
Error: Command failed: java -jar ./revanced/revanced-cli-2.7.1-all.jar -b ./revanced/revanced-patches-2.25.2.jar --custom-aapt2-binary revanced/aapt2 -t ./revanced-cache --experimental -a ./revanced/youtube.apk  -o ./revanced/revanced.apk  -m ./revanced/app-release-unsigned.apk  -e custom-branding
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
        at brut.androlib.res.decoder.Res9patchStreamDecoder$OtherImpl.decode(Res9patchStreamDecoder.java:203)
        at brut.androlib.res.decoder.Res9patchStreamDecoder.decode(Res9patchStreamDecoder.java:55)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:30)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:139)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:92)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:249)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
        at app.revanced.patcher.Patcher.<init>(Patcher.kt:68)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:141)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'java -jar ./revanced/revanced-cli-2.7.1-all.jar -b ./revanced/revanced-patches-2.25.2.jar --custom-aapt2-binary revanced/aapt2 -t ./revanced-cache --experimental -a ./revanced/youtube.apk  -o ./revanced/revanced.apk  -m ./revanced/app-release-unsigned.apk  -e custom-branding ',
  stdout: 'INFO: Decoding resources \n',
  stderr: `Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.\n` +
    '\tat java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)\n' +
    '\tat java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)\n' +
    '\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:318)\n' +
    '\tat java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)\n' +
    '\tat java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)\n' +
    '\tat java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)\n' +
    '\tat java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)\n' +
    '\tat java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)\n' +
    '\tat java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)\n' +
    '\tat brut.androlib.res.decoder.Res9patchStreamDecoder$OtherImpl.decode(Res9patchStreamDecoder.java:203)\n' +
    '\tat brut.androlib.res.decoder.Res9patchStreamDecoder.decode(Res9patchStreamDecoder.java:55)\n' +
    '\tat brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:30)\n' +
    '\tat brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:139)\n' +
    '\tat brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:92)\n' +
    '\tat brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:249)\n' +
    '\tat brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)\n' +
    '\tat app.revanced.patcher.Patcher.<init>(Patcher.kt:68)\n' +
    '\tat app.revanced.cli.command.MainCommand.run(MainCommand.kt:141)\n' +
    '\tat picocli.CommandLine.executeUserObject(CommandLine.java:1939)\n' +
    '\tat picocli.CommandLine.access$1300(CommandLine.java:145)\n' +
    '\tat picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)\n' +
    '\tat picocli.CommandLine$RunLast.handle(CommandLine.java:2352)\n' +
    '\tat picocli.CommandLine$RunLast.handle(CommandLine.java:2314)\n' +
    '\tat picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)\n' +
    '\tat picocli.CommandLine$RunLast.execute(CommandLine.java:2316)\n' +
    '\tat picocli.CommandLine.execute(CommandLine.java:2078)\n' +
    '\tat app.revanced.cli.main.MainKt.main(Main.kt:7)\n'
}

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...  
```

</details>

**Comment by reisxd** [comment]
Weird, this shouldn't happen because revanced-cli is a CLI application, not a GUI app. I have no idea why this could happen...

**Comment by akiyuee** [comment]
@reisxd I also have tigervnc installed but there was no instances running at that moment...

![Screenshot_20220728-183452_Termux](https://user-images.githubusercontent.com/67498765/181495717-bad1443e-45f2-4437-abb5-05c5b87754b8.jpg)

**Comment by akiyuee** [comment]
As of now a temporary solution is by opening a VNC server at `:1` to prevent this error.

**Comment by shrihanDev** [comment]
@akiyuee Can you run the following?

```bash
~/etc/revanced-builder-cli $ java -jar ./revanced/revanced-cli-2.7.1-all.jar -b ./revanced/revanced-patches-2.25.2.jar --custom-aapt2-binary ./revanced/aapt2 -t ./revanced-cache --experimental -a ./revanced/youtube.apk -o ./revanced/revanced.apk -m ./revanced/app-release-unsigned.apk -e custom-branding
```

**Comment by akiyuee** [comment]
@shrihanDev still error

![Screenshot_20220728-212139_Termux](https://user-images.githubusercontent.com/67498765/181539824-58503b07-3e54-4eeb-9614-032cc625722a.jpg)

**Comment by WatermelonOof** [comment]
What about running `unset DISPLAY`?

**Comment by akiyuee** [comment]
@WatermelonOof hmm, let me try it when I get home...

**Comment by akiyuee** [comment]
@WatermelonOof it built successfully. Thanks so much!
